from src.vaes_missing_values_in_pytorch.binarized_mnist import binarized_mnist
from src.vaes_missing_values_in_pytorch.cifar10 import cifar10
from src.vaes_missing_values_in_pytorch.mnist import mnist
from src.vaes_missing_values_in_pytorch.movielens import movielens
from src.vaes_missing_values_in_pytorch.omniglot import omniglot
from src.vaes_missing_values_in_pytorch.orl_faces import orl_faces
from src.vaes_missing_values_in_pytorch.yale_faces import yale_faces
